### ISSUE TITLE
Doesn't create dirs automatically.

### ISSUE THREAD

**Issue by luckcolors** [portablejim/Jims-Mod-Manager#1]
Hello.
I've got an suggestion and a bug to report :).
1. Please add the info about installing dependency "appdirs" and "requests" need to run this python script
2. Make the python script able to create a folder if needed like: The program needs to download a file in C:\modpack\mods\file..... if the folder mods is missing the program will return error.
3 Also could you make the cache portable? I mean stored in the folder of the python script?

**Comment by portablejim** [comment]
Is this in the wrong project? This one is a java based thing.
You may have wanted https://github.com/portablejim/curseDownloader

**Comment by luckcolors** [comment]
yeah sorry....

**Comment by luckcolors** [comment]
This issue was moved to portablejim/curseDownloader#3
